"use client";
import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { RecoveryForm } from "./recovery-form";
type C={id:string;authorId:string;author:string;avatar:string;avatarUrl?:string;text:string;likes:number;age:string;owner?:boolean};
type Video={id:string;title:string;channel:string;thumbnail?:string;totalComments:number};
const sample:C[]=[
{id:"1",authorId:"a1",author:"Maya Creates",avatar:"MC",text:"ENTER — the lighting breakdown at 4:12 was exactly what I needed!",likes:32,age:"2 hours ago"},
{id:"2",authorId:"a2",author:"Jordan Lee",avatar:"JL",text:"How do you keep the background sharp while filming handheld?",likes:18,age:"3 hours ago"},
{id:"3",authorId:"a3",author:"Studio North",avatar:"SN",text:"ENTER. Great tutorial and a genuinely useful giveaway.",likes:11,age:"5 hours ago"},
{id:"4",authorId:"a4",author:"Alex R.",avatar:"AR",text:"This saved me hours of trial and error. Thank you!",likes:9,age:"6 hours ago"},
{id:"5",authorId:"a5",author:"Priya Films",avatar:"PF",text:"ENTER — would love to use this for my first documentary.",likes:7,age:"8 hours ago"},
{id:"6",authorId:"a1",author:"Maya Creates",avatar:"MC",text:"ENTER! Forgot to say I subscribed too.",likes:4,age:"9 hours ago"},
{id:"7",authorId:"a6",author:"Cam & Coffee",avatar:"CC",text:"Could you make a follow-up about audio settings?",likes:21,age:"11 hours ago"},
{id:"8",authorId:"a7",author:"Diego Visuals",avatar:"DV",text:"ENTER. The color grading tips were excellent.",likes:15,age:"1 day ago"},
{id:"9",authorId:"owner",author:"Framecraft",avatar:"FC",text:"Thanks everyone — winner will be announced Friday!",likes:42,age:"1 day ago",owner:true},
{id:"10",authorId:"a8",author:"Nina Shoots",avatar:"NS",text:"ENTER — fingers crossed!",likes:3,age:"1 day ago"},
{id:"11",authorId:"a9",author:"Everyday Lens",avatar:"EL",text:"What lens did you use for the opening shot?",likes:13,age:"2 days ago"},
{id:"12",authorId:"a10",author:"Thomas K.",avatar:"TK",text:"ENTER. Clean, concise and useful.",likes:2,age:"2 days ago"}];
function downloadCsv(out:string,filename:string){const u=URL.createObjectURL(new Blob([out],{type:"text/csv"}));const a=document.createElement("a");a.href=u;a.download=filename;a.click();URL.revokeObjectURL(u)}
function csv(rows:C[]){const q=(v:string|number)=>`"${String(v).replaceAll('"','""')}"`;downloadCsv(["author,comment,likes,posted",...rows.map(c=>[c.author,c.text,c.likes,c.age].map(q).join(","))].join("\n"),"youtube-comments.csv")}
function giveawayCsv(winner:C,eligible:number,keyword:string){const q=(v:string|number)=>`"${String(v).replaceAll('"','""')}"`;downloadCsv([["result","CommentHarbor fair giveaway winner"],["winner",winner.author],["comment",winner.text],["required phrase",keyword||"None"],["eligible entries",eligible],["selected at",new Date().toISOString()],["verified with","https://commentharbor.com"]].map(row=>row.map(q).join(",")).join("\n"),"commentharbor-giveaway-winner.csv")}
function track(event:"export"|"giveaway_draw",metadata:Record<string,string|number|boolean>={}){void fetch("/api/analytics",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({event,metadata}),keepalive:true}).catch(()=>{})}
export default function Home(){
 const[url,setUrl]=useState("");const[comments,setComments]=useState<C[]>(sample);const[video,setVideo]=useState<Video|null>(null);const[loaded,setLoaded]=useState(false);const[loading,setLoading]=useState(false);const[error,setError]=useState("");const[paid,setPaid]=useState(false);const[notice,setNotice]=useState("");const[tab,setTab]=useState<"comments"|"giveaway">("comments");const[q,setQ]=useState("");const[questions,setQuestions]=useState(false);const[unique,setUnique]=useState(false);const[keyword,setKeyword]=useState("ENTER");const[winner,setWinner]=useState<C|null>(null);const[winnerHistory,setWinnerHistory]=useState<string[]>([]);const data=comments;
 useEffect(()=>{const p=new URLSearchParams(location.search);const session=p.get("session_id");const recovery=p.get("recovery");const sharedVideo=p.get("video");if(sharedVideo)queueMicrotask(()=>setUrl(sharedVideo));if(p.get("checkout")==="success"&&session){fetch(`/api/billing/verify?session_id=${encodeURIComponent(session)}`).then(r=>r.json()).then(x=>{if(x.paid){setPaid(true);setNotice("Lifetime access unlocked. Welcome to CommentHarbor Pro!");window.history.replaceState({},"",location.pathname)}})}else fetch("/api/billing/status").then(r=>r.json()).then(x=>{const hasAccess=Boolean(x.paid);setPaid(hasAccess);if(hasAccess&&recovery){if(recovery==="success")setNotice("Purchase restored. CommentHarbor Pro is unlocked on this browser.");window.history.replaceState({},"",location.pathname)}}).catch(()=>{})},[]);
 const filtered=useMemo(()=>{let r=comments.filter(c=>!q||`${c.author} ${c.text}`.toLowerCase().includes(q.toLowerCase()));if(questions)r=r.filter(c=>c.text.includes("?"));if(unique)r=r.filter((c,i,a)=>a.findIndex(x=>x.authorId===c.authorId)===i);return r},[comments,q,questions,unique]);
 const eligible=useMemo(()=>{const seen=new Set<string>();return comments.filter(c=>{if(keyword&&!c.text.toLowerCase().includes(keyword.toLowerCase()))return false;if(c.owner||seen.has(c.authorId))return false;seen.add(c.authorId);return true})},[comments,keyword]);
 function draw(){const fresh=eligible.filter(c=>!winnerHistory.includes(c.authorId)),pool=fresh.length?fresh:eligible;if(!pool.length)return;const n=new Uint32Array(1);crypto.getRandomValues(n);const w=pool[n[0]%pool.length];setWinner(w);setWinnerHistory(h=>[...h,w.authorId]);track("giveaway_draw",{eligible_count:eligible.length,reroll:Boolean(winner)})}
 async function analyze(){if(!url.trim())return;setLoading(true);setError("");try{const r=await fetch("/api/youtube/comments",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({url})});const x=await r.json();if(!r.ok)throw new Error(x.error||"Comments could not be loaded.");setComments(x.comments);setVideo(x.video);setPaid(Boolean(x.paid));setWinner(null);setLoaded(true)}catch(e){setError(e instanceof Error?e.message:"Comments could not be loaded.")}finally{setLoading(false)}}
 async function checkout(){setError("");const r=await fetch("/api/checkout",{method:"POST"});const x=await r.json();if(x.url)location.href=x.url;else setError(x.error||"Checkout could not be started.")}
 return <main>
  <header><Link className="brand" href="/"><b>CH</b>CommentHarbor</Link><nav><a href="#how">How it works</a><a href="#pricing">Pricing</a><span className={paid?"pro":"free"}>{paid?"PRO UNLOCKED":"FREE PLAN"}</span></nav></header>
  {notice&&<div className="notice">✓ {notice}</div>}
  <section className="hero" id="tool"><span className="eyebrow">● &nbsp; BUILT FOR VIDEO CREATORS</span><h1>Turn comments into<br/><em>clear next steps.</em></h1><p>Search, filter, export, and pick fair giveaway winners from any public YouTube video—without wrestling with spreadsheets.</p><div className="import"><i>CH</i><input aria-label="YouTube video URL" value={url} onChange={e=>setUrl(e.target.value)} onKeyDown={e=>e.key==="Enter"&&analyze()} placeholder="Paste a YouTube video URL"/><button onClick={analyze} disabled={loading}>{loading?"Loading comments…":"Analyze comments →"}</button></div>{error&&<p className="error">{error}</p>}<div className="trust"><span>✓ No credit card</span><span>✓ First 100 comments free</span><span>✓ We don’t store comments</span></div></section>
  {!loaded?<section className="preview" id="how"><div><span className="label">01</span><h2>Everything in one<br/>focused workspace.</h2><p>Find audience questions, collect testimonials, export research, or run a transparent giveaway in minutes.</p><button className="link" onClick={()=>{setComments(sample);setVideo({id:"demo",title:"10 Filmmaking Tricks That Changed My Videos",channel:"Framecraft",totalComments:12});setLoaded(true)}}>Try the interactive demo ↗</button></div><div className="mock"><div className="dots">● ● ● &nbsp; Comments · Framecraft</div>{sample.slice(0,3).map((c,i)=><div className={`mini ${i===0?"on":""}`} key={c.id}><b>{c.avatar}</b><div><strong>{c.author}</strong><p>{c.text}</p></div><small>♡ {c.likes}</small></div>)}<div className="ready"><span>GIVEAWAY READY</span><b>8 eligible · duplicates removed</b></div></div></section>:
  <section className="app"><div className="video"><button onClick={()=>setLoaded(false)}>←</button>{video?.thumbnail?<img className="thumbimg" src={video.thumbnail} alt=""/>:<div className="thumb">▶</div>}<div><span>{video?.id==="demo"?"DEMO DATA":paid?"PRO IMPORT":"FREE IMPORT"}</span><h2>{video?.title}</h2><p>{video?.channel} · {comments.length}{video&&video.totalComments>comments.length?` of ${video.totalComments.toLocaleString()}`:""} comments loaded</p></div><button className="export" onClick={()=>{if(paid){csv(filtered);track("export",{row_count:filtered.length,kind:"comments"})}else document.getElementById("pricing")?.scrollIntoView()}}>↓ {paid?"Export CSV":"Unlock export"}</button></div><div className="tabs"><button className={tab==="comments"?"active":""} onClick={()=>setTab("comments")}>Comment explorer</button><button className={tab==="giveaway"?"active":""} onClick={()=>setTab("giveaway")}>Giveaway picker <b>{eligible.length}</b></button></div>
  {tab==="comments"?<div className="explorer"><aside><label>SEARCH COMMENTS<input value={q} onChange={e=>setQ(e.target.value)} placeholder="Keyword or creator…"/></label><h3>Quick filters</h3><label className="check"><input type="checkbox" checked={questions} onChange={e=>setQuestions(e.target.checked)}/> Questions only</label><label className="check"><input type="checkbox" checked={unique} onChange={e=>setUnique(e.target.checked)}/> One per creator</label><div className="insight"><b>? &nbsp; 3 audience questions</b><p>Potential ideas for your next video.</p></div></aside><div><div className="results"><b>{filtered.length} comments</b><span>Sorted by most relevant</span></div>{filtered.map(c=><article key={c.id}><b className="avatar">{c.avatar}</b><div><h3>{c.author} <span>· {c.age}</span></h3><p>{c.text}</p><small>♡ {c.likes} likes</small></div></article>)}{!filtered.length&&<div className="empty">No comments match those filters.</div>}</div></div>:
  <div className="giveaway"><aside className="rules"><span className="label">GIVEAWAY RULES</span><h2>Set who is eligible.</h2><label>Required word or phrase<input value={keyword} onChange={e=>{setKeyword(e.target.value);setWinner(null)}}/></label><label className="check"><input type="checkbox" checked readOnly/> Exclude channel owner</label><label className="check"><input type="checkbox" checked readOnly/> Count each account once</label><div className="count"><strong>{eligible.length}</strong><span>eligible creators<br/><small>{data.length-eligible.length} comments excluded</small></span></div></aside><div className="draw">{!winner?<><div className="spark">✦</div><h2>Ready for a fair draw?</h2><p>We’ll randomly select one winner from {eligible.length} unique eligible creators.</p><button onClick={draw}>Pick a winner</button><small>Uses your browser’s secure random generator.</small></>:<><div className="confetti">✦ · ✦ · ✦</div><span className="label">WINNER SELECTED</span><b className="winneravatar">{winner.avatar}</b><h2>{winner.author}</h2><blockquote>“{winner.text}”</blockquote><div><button onClick={draw}>Reroll winner</button><button className="outline" onClick={()=>{giveawayCsv(winner,eligible.length,keyword);track("export",{row_count:1,kind:"giveaway_result"})}}>Download result</button></div><small>{new Date().toLocaleString()} · {eligible.length} eligible entries</small><a className="winner-proof" href="https://commentharbor.com">Winner selected fairly with CommentHarbor.com</a></>}</div></div>}</section>}
  <section className="pricing" id="pricing"><span className="label">LAUNCH PLAN</span><h2>{paid?"You have lifetime access.":"Start free. Upgrade when it earns its keep."}</h2><div><p><strong>{paid?"✓":"$19"}</strong> {paid?"CommentHarbor Pro unlocked":"lifetime early access"}</p><span>Up to 1,000 comments · CSV exports · Giveaway tools · Future updates</span><button onClick={checkout} disabled={paid}>{paid?"Purchased":"Unlock lifetime access →"}</button></div><RecoveryForm paid={paid}/></section>
  <footer><Link className="brand" href="/"><b>CH</b>CommentHarbor</Link><p>Built for creators who value their audience.</p><span className="footer-links"><a href="/youtube-comment-picker">Comment picker</a> · <a href="/youtube-giveaway-picker">Giveaway picker</a> · <a href="/youtube-comment-exporter">Comment exporter</a> · <a href="/youtube-comment-search">Comment search</a><br/><a href="/privacy">Privacy</a> · <a href="/terms">Terms</a> · <a href="/giveaway-disclaimer">Giveaway disclaimer</a></span></footer>
 </main>}
